name: Publish apk

on:
  push:
    branches:
      - 'master'

jobs:
  debug-apk:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: bash ./gradlew assembleDebug

      - uses: actions/upload-artifact@v1
        with:
          name: stopcovid-debug
          path: stopcovid/build/outputs/apk/debug/stopcovid-debug.apk

      - uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: stopcovid-debug
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: stopcovid/build/outputs/apk/debug/stopcovid-debug.apk
          asset_name: stopcovid-debug.apk
          asset_content_type: application/vnd.android.package-archive
