on:
  push:
    branches:
      - 'master'

jobs:
  debug-apk:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - run: bash ./gradlew assembleDebug

      - uses: actions/upload-artifact@v1
        with:
          name: stopcovid-debug
          path: stopcovid/build/outputs/apk/debug/stopcovid-debug.apk
