name: Publish apk

on:
  push:
    tags:
      - '*'

jobs:
  publish-apk:
    runs-on: ubuntu-18.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      APK_PATH: stopcovid/build/outputs/apk/release/stopcovid-release.apk

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - run: base64 -d > stopcovid/my-release-key.jks
             <<< "${{ secrets.KEYSTORE }}"

      - run: make build

      - uses: actions/upload-artifact@v1
        with:
          name: stopcovid-release
          path: ${{ env.APK_PATH }}

      - uses: actions/create-release@v1
        id: create_release
        with:
          tag_name: ${{ github.ref }}
          release_name: stopcovid ${{ github.ref }}
          draft: false
          prerelease: false

      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.APK_PATH }}
          asset_name: stopcovid-release.apk
          asset_content_type: application/vnd.android.package-archive
